# Generated by Django 5.2.5 on 2025-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('bola biasa', 'Bola Biasa'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('bola luar biasa', 'Bola Luar Biasa'), ('kolektor', 'Kolektor'), ('signed', 'Signed')], default='update', max_length=20),
        ),
    ]
