# Generated by Django 5.2.5 on 2025-09-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
