# Generated by Django 5.2.5 on 2025-09-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user',
            new_name='seller',
        ),
    ]
